import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveOgRenderBinary, renderHtmlToImage } from '../src/render-native.ts'
import { templateCatalog, renderTemplateHtml } from './template-catalog.ts'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const EXAMPLES_DIR = join(ROOT, 'examples')
const WWW_EXAMPLES_DIR = join(ROOT, 'www/public/examples')
const GENERATED_MODULE = join(ROOT, 'www/templates.generated.js')

const catalog = []
const canRender = process.platform === 'darwin' && (await resolveOgRenderBinary())

await mkdir(EXAMPLES_DIR, { recursive: true })
await mkdir(WWW_EXAMPLES_DIR, { recursive: true })

if (!canRender) {
  console.log('Skipping PNG export — og-render requires macOS (using committed PNGs)')
}

for (const entry of templateCatalog) {
  const html = renderTemplateHtml(entry.id)
  if (!html) continue

  const pngName = entry.png.replace('/examples/', '')

  catalog.push({
    id: entry.id,
    html,
    png: entry.png,
    description: entry.description,
    socialTitle: entry.socialTitle,
    config: entry.config,
  })

  if (!canRender) continue

  for (const dir of [EXAMPLES_DIR, WWW_EXAMPLES_DIR]) {
    const pngPath = join(dir, pngName)
    await renderHtmlToImage({ html, output: pngPath, scale: 1 })
    console.log(`✓ ${pngPath}`)
  }
}

const moduleSource = `// Generated by bun run export-previews — do not edit by hand
export const templateCatalog = ${JSON.stringify(catalog, null, 2)}
`

await writeFile(GENERATED_MODULE, moduleSource)
console.log(`✓ ${GENERATED_MODULE}`)

const review = Bun.spawnSync(['bun', 'scripts/review-pngs.ts'], {
  cwd: ROOT,
  stdout: 'inherit',
  stderr: 'inherit',
})
if (review.exitCode !== 0) {
  process.exit(review.exitCode ?? 1)
}